### PR TITLE
Update for version 2.3.0

### PR DESCRIPTION
**Pull request by cnweaver**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cnweaver** [comment]
@conda-forge-admin, please rerender

**Comment by myNameIsPatrick** [comment]
@cnweaver, this PR will need to be rebased after merging the v2.2.0 PR to resolve conflicts.

**Comment by cnweaver** [comment]
I think I have applied the necessary trivial fix?

**Review by myNameIsPatrick — APPROVED** [review]
LGTM

**Pull request merged**
